# Shallow Neural Network in Keras

Build a shallow neural network to classify MNIST digits

#### Set seed for reproducibility

In [1]:
import numpy as np
np.random.seed(42)

#### Load dependencies

In [2]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

Using TensorFlow backend.


#### Load data

In [3]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [4]:
X_train.shape

(60000, 28, 28)

In [5]:
y_train.shape

(60000,)

In [6]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0, 9,
       1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9, 3, 9,
       8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5, 6, 1, 0,
       0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9, 0, 4, 6, 7,
       4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [7]:
X_train.shape

(60000, 28, 28)

In [8]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [9]:
y_test.shape

(10000,)

In [10]:
y_test[0]

7

#### Preprocess data

In [11]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [12]:
X_train /= 255
X_test /= 255

In [13]:
X_test[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [14]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [15]:
y_train[0]

array([ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

#### Design neural network architecture

In [16]:
model = Sequential()
#i made big changes on this for fun and experimenting
model.add(Dense(320, activation='relu', input_shape=(784,)))
model.add(Dense(320, activation='relu', input_shape=(784,)))
model.add(Dense(320, activation='relu', input_shape=(784,)))
model.add(Dense(320, activation='relu', input_shape=(784,)))
model.add(Dense(10, activation='softmax'))


In [17]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 320)               251200    
_________________________________________________________________
dense_2 (Dense)              (None, 320)               102720    
_________________________________________________________________
dense_3 (Dense)              (None, 320)               102720    
_________________________________________________________________
dense_4 (Dense)              (None, 320)               102720    
_________________________________________________________________
dense_5 (Dense)              (None, 10)                3210      
Total params: 562,570
Trainable params: 562,570
Non-trainable params: 0
_________________________________________________________________


In [18]:
(64*784)

50176

In [19]:
(64*784)+64

50240

In [20]:
(10*64)+10

650

#### Configure model

In [21]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

#### Train!

In [22]:
model.fit(X_train, y_train, batch_size=128, epochs=100, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/100
60000/60000 [==============================] - 4s - loss: 0.0900 - acc: 0.1434 - val_loss: 0.0898 - val_acc: 0.1616
Epoch 2/100
60000/60000 [==============================] - 4s - loss: 0.0896 - acc: 0.1830 - val_loss: 0.0895 - val_acc: 0.2050
Epoch 3/100
60000/60000 [==============================] - 4s - loss: 0.0893 - acc: 0.2287 - val_loss: 0.0891 - val_acc: 0.2536
Epoch 4/100
60000/60000 [==============================] - 4s - loss: 0.0889 - acc: 0.2771 - val_loss: 0.0887 - val_acc: 0.2990
Epoch 5/100
60000/60000 [==============================] - 4s - loss: 0.0885 - acc: 0.3211 - val_loss: 0.0882 - val_acc: 0.3429
Epoch 6/100
60000/60000 [==============================] - 4s - loss: 0.0880 - acc: 0.3617 - val_loss: 0.0877 - val_acc: 0.3843
Epoch 7/100
60000/60000 [==============================] - 4s - loss: 0.0874 - acc: 0.4039 - val_loss: 0.0870 - val_acc: 0.4282
Epoch 8/100
60000/60000 [=============================

60000/60000 [==============================] - 4s - loss: 0.0133 - acc: 0.9157 - val_loss: 0.0128 - val_acc: 0.9185
Epoch 65/100
60000/60000 [==============================] - 4s - loss: 0.0132 - acc: 0.9166 - val_loss: 0.0127 - val_acc: 0.9195
Epoch 66/100
60000/60000 [==============================] - 4s - loss: 0.0131 - acc: 0.9173 - val_loss: 0.0126 - val_acc: 0.9202
Epoch 67/100
60000/60000 [==============================] - 4s - loss: 0.0130 - acc: 0.9178 - val_loss: 0.0125 - val_acc: 0.9206
Epoch 68/100
60000/60000 [==============================] - 4s - loss: 0.0129 - acc: 0.9182 - val_loss: 0.0125 - val_acc: 0.9207
Epoch 69/100
60000/60000 [==============================] - 4s - loss: 0.0129 - acc: 0.9187 - val_loss: 0.0124 - val_acc: 0.9211
Epoch 70/100
60000/60000 [==============================] - 4s - loss: 0.0128 - acc: 0.9196 - val_loss: 0.0123 - val_acc: 0.9212
Epoch 71/100
60000/60000 [==============================] - 4s - loss: 0.0127 - acc: 0.9197 - val_loss: 0.0122

In [23]:
model.evaluate(X_test, y_test)

 9600/10000 [===========================>..] - ETA: 0s

[0.010651165141433012, 0.93210000000000004]